#	$NetBSD: Makefile,v 1.1 1999/07/22 01:03:20 mrg Exp $

SCRIPTS=	wtf
SCRIPTSDIR=	${PREFIX}/bin
SHAREDIR?=	${PREFIX}/share
MANDIR?=	${SHAREDIR}/man/man
FILES= 		acronyms acronyms.comp
FILESDIR?=	${SHAREDIR}/games
MAN=		wtf.6

.include <bsd.prog.mk>
